---
- name: ansible-playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Configure hostname
      include_role:
        name: hostname
      when: provider != 'docker'
    - name: Configure users
      include_role:
        name: users
