---
- name: create users with password
  become: true
  become_method: sudo
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: on_create
  with_items: "{{ users }}"
